#!/usr/bin/env bash
# cd /Users/chensi/Simulations/data/elegant/hxfel/2.dba1/run

# mpirun -np 4 Pelegant kicker.ele
elegant kicker.ele
# sddsprocess kicker.sig -retain=column,St,Sdelta,s,ElementName -noWarnings
# sddsprocess kicker.fin -retain=parameter,St,Sdelta -noWarnings
# sddsprocess kicker.twi  -retain=column,s,beta?,alpha?,eta?,eta?p -retain=parameter, -noWarnings
# for i in {3,5}
# do
# sddsprocess kicker.w0$i -process=dt,average,t -define=column,dp,"p pCentral - pCentral /" -redefine=column,dt,"dt t -" \
# 	-retain=parameter,s,pCentral,PreviousElementName -retain=column,p,dt,x,y -noWarnings
# sddshist kicker.w0$i -pipe=output -dataColumn=dt -bins=500 -statistics | sddsprocess -pipe=input runParticleHist.w0$i -define=column,particleNum,"frequency"
#
# sddsplot kicker.w0$i -column=dt,dp -topline='Longitudinal Phase Space_w0'$i  -graphic=dot
# sddsplot runParticleHist.w0$i -column=dt,frequency -topline='Longitudinal Particle Distribition_w0'$i -graphic=line -yLabel='Num of Particle'
# sddsplot kicker.w0$i -column=x,y -topline='Transverse Phase Space_w0'$i  -graphic=dot
#
# sddsconvert kicker.w0$i runW0$i.Asc -ascii
# sddsconvert runParticleHist.w0$i runParticleHistW0$i.Asc -ascii
# done


# sddsplot kicker.twi -column=s,beta? -topline='Beta' -graph=line,vary -legend
# sddsplot kicker.twi -column=s,alpha? -topline='Alpha' -graph=line,vary -legend
# sddsplot kicker.twi -column=s,eta? -topline='Dispersion' -graph=line,vary -legend
# sddsplot kicker.twi -column=s,eta?p -topline="Dispersion'" -graph=line,vary -legend

# sddsplot kicker.sig -column=s,St
# sddsplot kicker.sig -column=s,Sdelta

# sddsconvert kicker.fin runFin.Asc -ascii
# sddsconvert kicker.twi runTwi.Asc -ascii
# sddsconvert kicker.sig runSig.Asc -ascii
# sddsconvert kicker.out runOut.Asc -ascii
# sddsconvert kicker.cen runCen.Asc -ascii

# mv kicker.w0* out/kick/

sddsxref out/kick/kicker.twi out/kick/kicker.sig out/kick/kicker.chs -take=ecnx,ecny,enx,eny,St,Sdelta
sddsxref out/kick/kicker.chs out/kick/kicker.flr out/kick/kicker.chs -take=X,Y,Z,theta,psi,phi
sddsxref out/kick/kicker.chs out/kick/kicker.cen out/kick/kicker.chs -take=Cx,Cy
sddsxref out/kick/kicker.chs out/kick/kicker.mag out/kick/kicker.chs -take=Profile
sddsxref out/kick/kicker.chs out/kick/kicker.mat out/kick/kicker.chs -take=R56
sddsprocess out/kick/kicker.chs -define=col,sigx,"enx pCentral0 / betax * Sdelta etax * sqr + sqrt 16 *",units=m -define=col,sigy,"eny pCentral0 / betay * Sdelta etay * sqr + sqrt 16 *",units=m
sddsprocess out/kick/kicker.chs -define=col,CXx,"X Cx +",units=m -define=col,CYy,"Y Cy +",units=m
sdds2plaindata out/kick/kicker.chs ../dat/kick/kick.dat -noRowCount -col=s "-separator= " -col=ElementName -col=betax -col=Y -col=Cy -col=CYy -col=betay -col=etax -col=etay -col=etaxp -col=etayp
sdds2plaindata out/kick/kicker.chs ../dat/kick/floor.dat -noRowCount -col=s "-separator= " -col=X -col=Cx -col=CXx -col=Y -col=Cy -col=CYy -col=Z -col=theta -col=psi -col=phi
sddsprintout -col="(s,ElementName,ElementType,beta*,alpha*,eta*,psi*,en*,pCentral0)" out/kick/kicker.chs -width=1000 ../dat/kick/twiss.dat
sdds2plaindata out/kick/kicker.mag ../dat/kick/prof.dat -noRowCount "-separator= " -col=s -col=Profile
sdds2plaindata out/kick/kicker.flr ../dat/flr/kick-flr.dat -col=ElementName -noRowCount "-separator= " -col=s -col=X -col=Y -col=Z -col=theta -col=phi -col=psi

# elegant2genesis linac/lhon2.sdds linac/lhon2.gen -totalCharge=1e-10 -chargeParameter=Charge -slices=1000
# sdds2plaindata linac/lhon2.gen ../dat/kick/current0.dat -noRowCount -col=s "-separator= " -col=t -col=current
# elegant2genesis out/kick/kicker.w04 out/kick/kicker.gen -totalCharge=1e-10 -chargeParameter=Charge -slices=1000
# sdds2plaindata out/kick/kicker.gen ../dat/kick/current.dat -noRowCount -col=s "-separator= " -col=t -col=current
# sdds2plaindata out/kick/kicker.w04 ../dat/kick/t-p.dat -noRowCount "-separator= " -col=t -col=p

# ./dist.py

# cp current.dat lhon2-current.dat
# cd /Users/chensi/Simulations/data/elegant/hxfel/2.dba1
# sddsplot -col=s,sig? -topline='Beam Size' -graph=line,vary -legend kicker.twi
# sddsplot -col=s,current -topline='Current' -graph=line,vary -legend kicker.gen

# exec ../plt/kick.py