#!/usr/bin/env bash
# cd /Users/chensi/Simulations/data/elegant/hxfel/2.dba1/run

# mpirun -np 4 Pelegant ltu0.ele
elegant ltu0.ele

sddsxref out/ltu0/ltu0.twi out/ltu0/ltu0.sig out/ltu0/ltu0.chs -take=ecnx,ecny,enx,eny,St,Sdelta
sddsxref out/ltu0/ltu0.chs out/ltu0/ltu0.flr out/ltu0/ltu0.chs -take=X,Y,Z,theta,psi,phi
sddsxref out/ltu0/ltu0.chs out/ltu0/ltu0.cen out/ltu0/ltu0.chs -take=Cx,Cy
sddsxref out/ltu0/ltu0.chs out/ltu0/ltu0.mag out/ltu0/ltu0.chs -take=Profile
sddsxref out/ltu0/ltu0.chs out/ltu0/ltu0.mat out/ltu0/ltu0.chs -take=R56
sddsprocess out/ltu0/ltu0.chs -define=col,sigx,"enx pCentral0 / betax * Sdelta etax * sqr + sqrt 16 *",units=m -define=col,sigy,"eny pCentral0 / betay * Sdelta etay * sqr + sqrt 16 *",units=m
sddsprocess out/ltu0/ltu0.chs -define=col,CXx,"X Cx +",units=m -define=col,CYy,"Y Cy +",units=m
sdds2plaindata out/ltu0/ltu0.chs ../dat/ltu0/param.dat -noRowCount -col=s "-separator= " -col=ElementName -col=betax -col=Y -col=Cy -col=CYy -col=betay -col=etax -col=etay -col=etaxp -col=etayp
sdds2plaindata out/ltu0/ltu0.chs ../dat/ltu0/floor.dat -noRowCount -col=s "-separator= " -col=X -col=Cx -col=CXx -col=Y -col=Cy -col=CYy -col=Z -col=theta -col=psi -col=phi
sddsprintout -col="(s,ElementName,ElementType,beta*,alpha*,eta*,psi*,en*,pCentral0)" out/ltu0/ltu0.chs -width=1000 ../dat/ltu0/twiss.dat
sdds2plaindata out/ltu0/ltu0.mag ../dat/ltu0/prof.dat -noRowCount "-separator= " -col=s -col=Profile
sdds2plaindata out/ltu0/ltu0.flr ../dat/flr/kick-flr.dat -col=ElementName -noRowCount "-separator= " -col=s -col=X -col=Y -col=Z -col=theta -col=phi -col=psi

# elegant2genesis linac/lhon2.sdds linac/lhon2.gen -totalCharge=1e-10 -chargeParameter=Charge -slices=1000
# sdds2plaindata linac/lhon2.gen ../dat/kick/current0.dat -noRowCount -col=s "-separator= " -col=t -col=current
# elegant2genesis out/ltu0/ltu0.w04 out/ltu0/ltu0.gen -totalCharge=1e-10 -chargeParameter=Charge -slices=1000
# sdds2plaindata out/ltu0/ltu0.gen ../dat/kick/current.dat -noRowCount -col=s "-separator= " -col=t -col=current
# sdds2plaindata out/ltu0/ltu0.w04 ../dat/kick/t-p.dat -noRowCount "-separator= " -col=t -col=p

# ./dist.py

# cp current.dat lhon2-current.dat
# cd /Users/chensi/Simulations/data/elegant/hxfel/2.dba1
# sddsplot -col=s,sig? -topline='Beam Size' -graph=line,vary -legend ltu0.twi
# sddsplot -col=s,current -topline='Current' -graph=line,vary -legend ltu0.gen

# exec ../plt/kick.py