#!/usr/bin/env bash
# cd /Users/chensi/Simulations/data/elegant/hxfel/2.dba1/run

# mpirun -np 4 Pelegant ltu3.ele
elegant ltu3.ele

sddsxref out/ltu3/ltu3.twi out/ltu3/ltu3.sig out/ltu3/ltu3.chs -take=ecnx,ecny,enx,eny,St,Sdelta
sddsxref out/ltu3/ltu3.chs out/ltu3/ltu3.flr out/ltu3/ltu3.chs -take=X,Y,Z,theta,psi,phi
sddsxref out/ltu3/ltu3.chs out/ltu3/ltu3.cen out/ltu3/ltu3.chs -take=Cx,Cy
sddsxref out/ltu3/ltu3.chs out/ltu3/ltu3.mag out/ltu3/ltu3.chs -take=Profile
sddsxref out/ltu3/ltu3.chs out/ltu3/ltu3.mat out/ltu3/ltu3.chs -take=R56
	
sddsprocess out/ltu3/ltu3.chs -define=col,sigx,"enx pCentral0 / betax * Sdelta etax * sqr + sqrt 16 *",units=m -define=col,sigy,"eny pCentral0 / betay * Sdelta etay * sqr + sqrt 16 *",units=m
sddsprocess out/ltu3/ltu3.chs -define=col,CXx,"X Cx +",units=m -define=col,CYy,"Y Cy +",units=m

sdds2plaindata out/ltu3/ltu3.chs ../dat/ltu3/param.dat -noRowCount -col=s "-separator= " -col=ElementName -col=betax -col=Y -col=Cy -col=CYy -col=betay -col=etax -col=etay -col=etaxp -col=etayp
sdds2plaindata out/ltu3/ltu3.chs ../dat/ltu3/floor.dat -noRowCount -col=s "-separator= " -col=X -col=Cx -col=CXx -col=Y -col=Cy -col=CYy -col=Z -col=theta -col=psi -col=phi

sddsprintout -col="(s,ElementName,ElementType,beta*,alpha*,eta*,psi*,en*,pCentral0)" out/ltu3/ltu3.chs -width=1000 ../dat/ltu3/twiss.dat

sdds2plaindata out/ltu3/ltu3.mag ../dat/ltu3/prof.dat -noRowCount "-separator= " -col=s -col=Profile
sdds2plaindata out/ltu3/ltu3.flr ../dat/flr/ltu3-flr.dat -col=ElementName -noRowCount "-separator= " -col=s -col=X -col=Y -col=Z -col=theta -col=phi -col=psi
